enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  "@typescript-eslint/type-utils@*":
    dependencies:
      eslint: "*"
  "@typescript-eslint/utils@*":
    dependencies:
      typescript: "*"

pnpMode: strict

yarnPath: .yarn/releases/yarn-4.9.2.cjs
