/**
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by build scripts.
 * Any manual changes will be overwritten on the next build.
 *
 * To modify this file, update the generator script or templates.
 */

import { type ComponentTypeDictionary } from "@/lib/optimizely-cms";
import BlankExperienceComponent from "./BlankExperience/BlankExperienceIndex";

/**
 * ExperienceFactory - Auto-generated component registry
 *
 * This file is automatically generated by scripts/generate-factories.mjs
 * Run 'yarn generate:factories' to regenerate.
 */
export const ExperienceFactory: ComponentTypeDictionary = {
  "BlankExperience": BlankExperienceComponent,
};

// Export as default for convenience
export default ExperienceFactory;
