/**
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by scripts/generate-shared-fragments.mjs
 * Run 'yarn generate:fragments' to regenerate this file.
 *
 * Shared GraphQL Fragments
 *
 * These fragments are extracted from individual component .graphql files
 * and combined here for use in queries. This eliminates duplication and
 * ensures fragments stay in sync with component definitions.
 */

import { gql } from 'graphql-request';

/**
 * Core metadata fragments
 * These are hand-maintained as they define base interfaces
 */
export const CORE_FRAGMENTS = gql`
  fragment IContentData on _IContent {
    _metadata {
      ...IContentInfo
    }
    _type: __typename
  }

  fragment IContentInfo on IContentMetadata {
    key
    locale
    types
    displayName
    version
    url {
      ...LinkData
    }
  }

  fragment LinkData on ContentUrl {
    base
    default
  }

  fragment PageData on _IContent {
    ...IContentData
  }
`;

/**
 * Page type fragments (4 page(s))
 * Auto-generated from component .graphql files
 */
export const PAGE_FRAGMENTS = gql`
  fragment ArticlePageData on ArticlePage {
  _metadata {
    key
    version
    published
    lastModified
    displayName
    url {
      base
      default
    }
  }
  Heading
  Intro
  MainBody {
    html
  }
}

  fragment LandingPageData on LandingPage {
  _metadata {
    key
    version
    published
    lastModified
    displayName
    url {
      base
      default
    }
  }
  Title
  MetaDescription
  UrlSegment
  MainBody {
    html
  }
}

  fragment NewsPageData on NewsPage {
  _metadata {
    key
    version
    published
    lastModified
    displayName
    url {
      base
      default
    }
  }
  MainBody {
    html
  }
  MainContentArea {
    __typename
    _metadata {
      key
      displayName
    }
  }
}

  fragment StartPageData on StartPage {
  _metadata {
    key
    version
    published
    lastModified
    displayName
    url {
      base
      default
    }
  }
  Heading
  MainIntro
  MainContentArea {
    __typename
    _metadata {
      key
      displayName
    }
  }
}
`;

/**
 * Experience type fragments (1 experience(s))
 * Auto-generated from component .graphql files
 */
export const EXPERIENCE_FRAGMENTS = gql`
  fragment BlankExperienceData on BlankExperience {
  _metadata {
    key
  }
  composition {
    key
    displayName
    nodeType
    type
    displayTemplateKey
  }
}
`;

/**
 * Component/Block type fragments (4 component(s))
 * Auto-generated from component .graphql files
 */
export const COMPONENT_FRAGMENTS = gql`
  fragment ContentAreaData on ContentArea {
  _metadata {
    key
  }
}

  fragment HeroBlockData on HeroBlock {
  _metadata {
    key
    version
    published
    lastModified
    displayName
    url {
      base
      default
    }
  }
  Heading
  Image {
    url {
      default
    }
  }
  MainIntro
  ContentLink {
    url {
      default
    }
  }
  Width
}

  fragment SliderBlockData on SliderBlock {
  _metadata {
    key
    version
    published
    lastModified
    displayName
    url {
      base
      default
    }
  }
  SliderContent {
    __typename
    _metadata {
      key
      displayName
    }
  }
}

  fragment TextBlockData on TextBlock {
  _metadata {
    key
    version
    published
    lastModified
    displayName
    url {
      base
      default
    }
  }
  Text {
    html
  }
}
`;

/**
 * All fragments combined for easier import
 */
export const ALL_FRAGMENTS = gql`
  ${CORE_FRAGMENTS}
  ${PAGE_FRAGMENTS}
  ${EXPERIENCE_FRAGMENTS}
  ${COMPONENT_FRAGMENTS}
`;
