'use client';
// Auto generated dictionary
// @not-modified => When this line is removed, the "force" parameter of the CLI tool is required to overwrite this file

import { type CmsComponent } from "@/lib/optimizely-cms";
import { MyTestDataFragmentDoc, type MyTestDataFragment } from "@/gql/graphql";

/**
 * MyTest
 *
 */
export const MyTestComponent : CmsComponent<MyTestDataFragment> = ({ data, children }) => {
    return (
        <div className="relative min-h-screen overflow-hidden">
            {/* Animated background gradient */}
            <div className="absolute inset-0 bg-gradient-to-br from-blue-950 via-purple-950 to-slate-950">
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,_rgba(59,130,246,0.15),transparent_50%)]" />
                <div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_20%,_rgba(168,85,247,0.15),transparent_50%)]" />
            </div>

            {/* Content */}
            <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
                <div className="text-center space-y-8">
                    {/* Hero heading */}
                    <h1 className="text-6xl md:text-8xl font-bold">
                        <span className="bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent animate-pulse">
                            MyTest
                        </span>
                    </h1>

                    {/* Subtitle */}
                    <p className="text-2xl md:text-3xl text-slate-300 font-light max-w-3xl mx-auto">
                        Welcome to your custom page
                    </p>

                    {/* Description */}
                    <div className="max-w-2xl mx-auto space-y-6">
                        <p className="text-lg text-slate-400 leading-relaxed">
                            This page was automatically generated by the Proxima CLI tool.
                            The routing, component registration, and GraphQL queries were all created automatically.
                        </p>

                        {/* Feature cards */}
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-12">
                            <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6 hover:bg-white/10 transition-all hover:scale-105">
                                <div className="text-4xl mb-4">🚀</div>
                                <h3 className="text-xl font-semibold text-white mb-2">Automated</h3>
                                <p className="text-sm text-slate-400">No manual code changes needed</p>
                            </div>

                            <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6 hover:bg-white/10 transition-all hover:scale-105">
                                <div className="text-4xl mb-4">⚡</div>
                                <h3 className="text-xl font-semibold text-white mb-2">Fast</h3>
                                <p className="text-sm text-slate-400">From CMS to code in seconds</p>
                            </div>

                            <div className="bg-white/5 backdrop-blur-sm border border-white/10 rounded-2xl p-6 hover:bg-white/10 transition-all hover:scale-105">
                                <div className="text-4xl mb-4">🎨</div>
                                <h3 className="text-xl font-semibold text-white mb-2">Customizable</h3>
                                <p className="text-sm text-slate-400">Edit this component however you like</p>
                            </div>
                        </div>
                    </div>

                    {/* CTA Button */}
                    <div className="pt-8">
                        <a
                            href="/"
                            className="inline-block bg-gradient-to-r from-blue-500 to-purple-500 hover:from-blue-600 hover:to-purple-600 text-white font-semibold px-8 py-4 rounded-full transition-all hover:scale-105 shadow-lg shadow-purple-500/50"
                        >
                            Back to Home
                        </a>
                    </div>
                </div>

                {children}
            </div>
        </div>
    );
}
MyTestComponent.displayName = "MyTest (page/MyTest)"
MyTestComponent.getDataFragment = () => ['MyTestData', MyTestDataFragmentDoc]

export default MyTestComponent
