import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { getServerContext } from "@/lib/optimizely-cms/rsc";

import Header from "@/components/header";
import Footer from "@/components/footer";

const poppins = Poppins({
  weight: ['300', '400', '700'],
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Optimizely CMS Boilerplate - Create Next App",
  description: "Generated by create next app for Optimizely CMS",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { locale } = await getServerContext();
  return (
    <html lang={locale ?? "en"} className="scroll-smooth">
      <body className={`${poppins.className} antialiased`}>
        <div className="min-h-screen bg-[#DEE5E4]">
          <Header />
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
