/**
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by build scripts.
 * Any manual changes will be overwritten on the next build.
 *
 * To modify this file, update the generator script or templates.
 */

import { type ComponentTypeDictionary } from "@/lib/optimizely-cms";
import ArticlePageComponent from "./ArticlePage/ArticlePageIndex";
import LandingPageComponent from "./LandingPage/LandingPageIndex";
import NewsPageComponent from "./NewsPage/NewsPageIndex";
import StartPageComponent from "./StartPage/StartPageIndex";

/**
 * PageFactory - Auto-generated component registry
 *
 * This file is automatically generated by scripts/generate-factories.mjs
 * Run 'yarn generate:factories' to regenerate.
 */
export const PageFactory: ComponentTypeDictionary = {
  "ArticlePage": ArticlePageComponent,
  "LandingPage": LandingPageComponent,
  "NewsPage": NewsPageComponent,
  "StartPage": StartPageComponent,
};

// Export as default for convenience
export default PageFactory;
