#!/usr/bin/env node

/**
 * Shared configuration for all build scripts
 *
 * This file centralizes all hardcoded paths, naming conventions,
 * and configuration values used across the project's build scripts.
 */

import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Project paths configuration
 */
export const PATHS = {
  // Root directories
  projectRoot: path.resolve(__dirname, '..'),
  scriptsDir: path.resolve(__dirname),

  // Source directories
  src: 'src',
  components: 'src/components/cms',
  gql: 'src/gql',

  // CMS component directories
  cms: {
    component: 'src/components/cms/component',
    page: 'src/components/cms/page',
    experience: 'src/components/cms/experience',
  },

  // GraphQL directories
  graphql: {
    queries: 'src/gql/queries',
    fragments: 'src/gql/fragments',
    generated: 'src/gql/graphql.ts',
  },
};

/**
 * File naming conventions
 */
export const NAMING = {
  // Component file patterns
  indexFile: (name) => `${name}Index.tsx`,
  teaserFile: (name) => `${name}Teaser.tsx`,
  graphqlFile: (name) => `${name}.graphql`,
  contentTypeFile: (name) => `${name}.ts`,
  factoryFile: () => 'index.ts',

  // Component name suffixes
  suffixes: ['Page', 'Block', 'Experience', 'Component'],

  // Variable naming
  componentVar: (name) => `${name}Component`,
  teaserVar: (name) => `${name}Teaser`,

  // Base type mappings
  baseTypeMap: {
    page: '_page',
    component: '_component',
    experience: '_experience',
  },

  // Suffix generation by base type
  getSuffix: (baseType) => {
    switch (baseType) {
      case '_page': return 'Page';
      case '_experience': return 'Experience';
      case '_component':
      default: return 'Component';
    }
  },
};

/**
 * GraphQL type mappings
 */
export const GRAPHQL = {
  // Property type to GraphQL field mapping
  typeMapping: {
    // Rich text types
    richtext: (prop) => `  ${prop} {\n    html\n  }`,
    xhtmlstring: (prop) => `  ${prop} {\n    html\n  }`,

    // Media types
    image: (prop) => `  ${prop} {\n    url {\n      default\n    }\n  }`,

    // Reference types
    contentarea: (prop) => `  ${prop} {\n    __typename\n    _metadata {\n      key\n      displayName\n    }\n  }`,
    contentreference: (prop) => `  ${prop} {\n    __typename\n    _metadata {\n      key\n      displayName\n    }\n  }`,

    // Collection types
    array: (prop) => `  ${prop} {\n    __typename\n    _metadata {\n      key\n      displayName\n    }\n  }`,

    // Default scalar
    default: (prop) => `  ${prop}`,
  },

  // Property name hints for special handling
  propertyHints: {
    isImage: (propName) => propName.toLowerCase().includes('image'),
    isContentArea: (propName) => propName.toLowerCase().includes('contentarea'),
    isContentLink: (propName) => propName.toLowerCase().includes('contentlink'),
  },
};

/**
 * Registry configuration
 */
export const REGISTRY = {
  // Files to generate
  clientRegistry: 'src/components/cms/client-registry.ts',

  // Discovery patterns
  discovery: {
    components: {
      dir: 'component',
      filePattern: (name) => `${name}Index.tsx`,
      varName: (name) => `${name}Component`,
    },
    teasers: {
      dir: 'page',
      filePattern: (name) => `${name}Teaser.tsx`,
      varName: (name) => `${name}Teaser`,
    },
  },
};

/**
 * Build and script configuration
 */
export const BUILD = {
  // Timeouts (in milliseconds)
  defaultTimeout: 120000,

  // Script execution
  nodeCommand: 'node',

  // Validation settings
  validateComponentExports: true,
  strictMode: false,
};

/**
 * Template configuration
 */
export const TEMPLATES = {
  // Auto-generation warning
  autoGenWarning: `/**
 * ⚠️  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by build scripts.
 * Any manual changes will be overwritten on the next build.
 *
 * To modify this file, update the generator script or templates.
 */`,

  // Component metadata
  metadata: {
    required: ['_metadata', '__typename'],
    optional: ['displayName', 'key', 'url'],
  },
};

/**
 * Validation rules
 */
export const VALIDATION = {
  // Content type validation
  baseTypes: ['page', 'component', 'experience'],

  // File validation
  requiredFiles: {
    component: ['Index.tsx', '.graphql'],
    page: ['Index.tsx', 'Teaser.tsx', '.graphql'],
    experience: ['Index.tsx', '.graphql'],
  },
};

/**
 * Helper function to get absolute path
 */
export function getAbsolutePath(relativePath) {
  return path.join(PATHS.projectRoot, relativePath);
}

/**
 * Helper function to check if a component should have a teaser
 */
export function shouldHaveTeaser(baseType) {
  return baseType === '_page' || baseType === 'page';
}

/**
 * Helper function to get component type from base type
 */
export function getComponentType(baseType) {
  return NAMING.baseTypeMap[baseType] || baseType;
}

export default {
  PATHS,
  NAMING,
  GRAPHQL,
  REGISTRY,
  BUILD,
  TEMPLATES,
  VALIDATION,
  getAbsolutePath,
  shouldHaveTeaser,
  getComponentType,
};
